import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyComponent from "./boutique";
import Footer from "./footer"
import "./globals.css";
import dropdown from "./dropdown";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header /> {/* Ajout de l'importation du composant Header */}
        {children}
       
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
